import socket

SOURCE_IP_ADDR = '130.245.75.217'
ICMP_PACKET_FORMAT = "!BBHHH"
ICMP_ECHO_REQUEST = 8
ICMP_START_INDEX = 20
ICMP_END_INDEX = 28

SOCK_BUFFER_SIZE = 1024
TIMEOUT = 1

IP_INTERNET_HEADER_LENGTH = 5
IP_VERSION = 4
IP_TYPE_OF_SERVICE = 0
IP_INIT_LENGTH = 0
IP_FLAG_FRAG_OFFSET = 0
IP_TIME_TO_LIVE = 255
IP_INIT_CHECKSUM = 0

TCP_INIT_SEQ_NUM = 0
TCP_ACKNOWLEDGE_NUM = 0
TCP_DATA_OFFSET = 5
TCP_RESERVED = 0
TCP_FLAG_SET = 1
TCP_FLAG_UNSET = 0
TCP_HEADER_LEN = 80
TCP_MAX_WINDOW_SIZE = 5840
TCP_INIT_CHECKSUM = 0
TCP_URG_POINTER = 0
TCP_PAYLOAD = "CSE509:TCPSYNCPORTSCAN"
#TCP_PAYLOAD = ''
TCP_SOURCE_PORT = 65535

SOCK_BUFFER_SIZE = 65565
TIMEOUT = 1
MAX_TRIES = 3
MAX_PORTS_PER_THREAD = 25
MAX_THREADS = 100
